//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerkoLanguage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }

        public string BirthdayString
        {
            get
            {
                if (Birthday != null)
                {
                    return Birthday.ToShortDateString();
                }
                else
                    return "";
            }
        }

        public System.DateTime RegistrationDate { get; set; }

        public string RegistrationDateString
        {
            get
            {
                if (RegistrationDate != null)
                {
                    return RegistrationDate.ToShortDateString();
                }
                else
                    return "";
            }
        }

        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }

        public string GenderName
        {
            get
            {
                return Gender.Name;
            }
        }

        public int VisitCount
        {
            get
            {
                var datelist = ClientService.Where(p => p.ClientID == this.ID).ToList();
                return datelist.Count;
            }
        }

        public DateTime? LastVisitDate
        {
            get
            {
                var latestService = ClientService.Where(p => p.ClientID == this.ID).OrderByDescending(p => p.StartTime).FirstOrDefault();

                return latestService?.StartTime;
            }
        }

        public string LastVisitDateString
        {
            get
            {
                if (LastVisitDate.HasValue)
                {
                    return LastVisitDate.Value.ToShortDateString();
                }
                else
                    return "нет";
            }
        }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }


    }
}
